name: SlimeQuest
author: Mooy1
description: Questing and progression addon
main: io.github.mooy1.slimequest.SlimeQuest
website: https://github.com/Mooy1/SlimeQuest
depend: [Slimefun, CS-CoreLib]
softdepend: [InfinityExpansion, LiteXpansion, FluffyMachines, ExtraTools, SFCalc]
version: ${project.version}
api-version: 1.16

commands:
  slimequest:
    description: Do /slimequest help for a list of commands
    usage: /slimequest <subcommand>
    aliases: [sq, sfquest]

permissions:
  slimequest.admin:
    description: SlimeQuest admin commands
    default: op